[colophon]
= Informazioni sulla Guida

**Antonio Musarra,** Raspberry Pi e Smart Card Mifare Classic 1K - Guida pratica per realizzare un sistema di autenticazione con smart card contactless su Raspberry Pi

Copertina e impaginazione di Antonio Musarra

Prima edizione digitale Luglio 2024

Serie: Elettronica&Informatica (#elettronica-informatica)

[.text-left]
Promosso da: Antonio Musarra's Blog (https://www.dontesta.it)

Profilo LinkedIn https://www.linkedin.com/in/amusarra/

[.text-left]
Il progetto di esempio realizzato per quest'opera è disponibile sul repositoy GitHub all'indirizzo https://github.com/amusarra/smartcard-contactless-raspberry-pi

[.text-left]
Quest'opera è stata realizzata usando l'approccio doc-as-code e il testo è stato scritto in formato AsciiDoc.

Nel caso di errori, segnalazioni o suggerimenti, si prega di aprire una issue o discussione sul repository GitHub.

[.text-left]
Progetto Smart Card Contactless Raspberry Pi

[.text-left]
. Apertura issue https://github.com/amusarra/smartcard-contactless-raspberry-pi/issues
. Apertura discussione https://github.com/amusarra/smartcard-contactless-raspberry-pi/discussions

Nell'ambito del social coding e del contributo alla comunità, è possibile contribuire al progetto con una pull request per migliorare questa guida e il progetto di esempio.

[.text-left]
**Note sul Copyright**
Tutti i diritti d’autore e connessi sulla presente opera appartengono all’autore Antonio Musarra. Per volontà dell’autore quest’opera è rilasciata nei termini della licenza Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International il cui testo integrale è disponibile alla pagina web https://creativecommons.org/licenses/by-nc-sa/4.0/deed.it

Tutti i marchi riportati appartengo ai legittimi proprietari; marchi di terzi, nomi di prodotti, nomi commerciali, nomi corporativi e società citati possono essere marchi di proprietà dei rispettivi titolari o marchi registrati d’altre società e sono stati utilizzati a puro scopo esplicativo e a beneficio del possessore, senza alcun fine di violazione dei diritti di copyright vigenti.