<<<
== Implementare il software
Adesso che il **cosa** è chiaro, vediamo il **come**, rispondendo alle domande a seguire:

[.text-left]
1.  Quale linguaggio usare per implementare lo scenario che abbiamo descritto all'inizio dell'articolo? **Python**
2.  Esiste qualche libreria Python per la costruzione di applicazioni basate su Smart Card? https://pyscard.sourceforge.io/index.html[Pyscard]
3.  Quale tipo di database usare per la memorizzazione dei dati? https://www.mongodb.com/[MongoDB] (https://it.wikipedia.org/wiki/NoSQL[NoSQL] database)
4.  Esiste qualche libreria Python per operare con MongoDB? https://pymongo.readthedocs.io/en/stable/[PyMongo]
5.  Esiste qualche libreria Python per interagire con l'interfaccia GPIO del Raspberry Pi? https://pypi.org/project/RPi.GPIO/[RPi.GPIO]

Da questa lista le cose da fare sono parecchie e lo spazio per vederle tutte nel dettaglio in questo articolo non c'è. Direi quindi di focalizzare la nostra attenzione sui componenti da realizzare rimanendo ad alto livello, senza scendere nello specifico del codice.

[NOTE]
====
**Non vi allarmate!** Il progetto è già stato sviluppato prima di scrivere questo articolo e disponibile sul mio repository GitHub https://github.com/amusarra/smartcard-contactless-raspberry-pi[Smart Card Contactless Raspberry Pi].
====

[NOTE]
====
**Nota su MongoDB**. È necessario preparare un'istanza di MongoDB sul proprio Raspberry Pi affinché la soluzione funzioni nel modo corretto.Le scelte sono due: container docker o installazione classica direttamente sul sistema operativo. Personalmente ho scelto la strada di Docker (vedi 6. Requisiti Software), per cui, una volta https://docs.docker.com/engine/install/debian/[installato Docker sul proprio Raspberry Pi OS], i passi per tirare su un'istanza MongoDB 4.4.12 sono quelli indicati a seguire.
====

[source,shell,title="*Console 1* - Pull dell'immagine MongoDB 4.4.12 e run del container"]
....
# 1. Docker pull e run MongoDB 4.4.12
docker pull mongo:4.4.12
docker run -d -p 27017-27019:27017-27019 --name mongodb mongo:4.4.12

# 2. Verifica che l'istanza sia su e accesso alla console bash (task opzionale)
docker exec -it mongodb bash

# 3. Avvio della console MongoDB (task opzionale)
root@0d21da235b0d:/# mongo
....

Nel caso in cui preferiate perseguire la seconda strada, il blog di MongoDB riporta la procedura completa sull'articolo https://www.mongodb.com/developer/how-to/mongodb-on-raspberry-pi/[Install &amp; Configure MongoDB on the Raspberry Pi].